---
version: "3.7"

services:
  traefik:
    image: traefik:v2.5
    networks:
      ocis-net:
        aliases:
          - ${OCIS_DOMAIN:-ocis.owncloud.test}
          - ${WOPISERVER_COLLABORA_DOMAIN:-wopiserver-collabora.owncloud.test}
          - ${WOPISERVER_ONLYOFFICE_DOMAIN:-wopiserver-onlyoffice.owncloud.test}
          - ${COLLABORA_DOMAIN:-collabora.owncloud.test}
          - ${ONLYOFFICE_DOMAIN:-onlyoffice.owncloud.test}
    command:
      - "--log.level=${TRAEFIK_LOG_LEVEL:-ERROR}"
      # letsencrypt configuration
      - "--certificatesResolvers.http.acme.email=${TRAEFIK_ACME_MAIL:-example@example.org}"
      - "--certificatesResolvers.http.acme.storage=/certs/acme.json"
      - "--certificatesResolvers.http.acme.httpChallenge.entryPoint=http"
      # enable dashboard
      - "--api.dashboard=true"
      # define entrypoints
      - "--entryPoints.http.address=:80"
      - "--entryPoints.http.http.redirections.entryPoint.to=https"
      - "--entryPoints.http.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.https.address=:443"
      # docker provider (get configuration from container labels)
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/certs"
    labels:
      - "traefik.enable=${TRAEFIK_DASHBOARD:-false}"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASIC_AUTH_USERS:-admin:$$apr1$$4vqie50r$$YQAmQdtmz5n9rEALhxJ4l.}" # defaults to admin:admin
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN:-traefik.owncloud.test}`)"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.routers.traefik.tls.certresolver=http"
      - "traefik.http.routers.traefik.service=api@internal"
    logging:
      driver: "local"
    restart: always

  ocis:
    image: owncloud/ocis:${OCIS_DOCKER_TAG:-latest}
    networks:
      ocis-net:
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    environment:
      OCIS_URL: https://${OCIS_DOMAIN:-ocis.owncloud.test}
      OCIS_DOMAIN: ${OCIS_DOMAIN:-ocis.owncloud.test}
      OCIS_LOG_LEVEL: ${OCIS_LOG_LEVEL:-error} # make oCIS less verbose
      PROXY_TLS: "false" # do not use SSL between Traefik and oCIS
      # change default secrets
      IDP_LDAP_BIND_PASSWORD: ${IDP_LDAP_BIND_PASSWORD:-idp}
      STORAGE_LDAP_BIND_PASSWORD: ${STORAGE_LDAP_BIND_PASSWORD:-reva}
      OCIS_JWT_SECRET: ${OCIS_JWT_SECRET:-Pive-Fumkiu4}
      OCIS_MACHINE_AUTH_API_KEY: ${OCIS_MACHINE_AUTH_API_KEY:-change-me-please}
      OCIS_TRANSFER_SECRET: ${STORAGE_TRANSFER_SECRET:-replace-me-with-a-transfer-secret}
      # app registry
      STORAGE_GATEWAY_GRPC_ADDR: 0.0.0.0:9142 # make the REVA gateway accessible to the app drivers
      STORAGE_APP_REGISTRY_MIMETYPES_JSON: /var/tmp/ocis/app-config/mimetypes.json
      # INSECURE: needed if oCIS / Traefik is using self generated certificates
      OCIS_INSECURE: "${INSECURE:-false}"
      # basic auth (not recommended, but needed for eg. WebDav clients that do not support OpenID Connect)
      PROXY_ENABLE_BASIC_AUTH: "${PROXY_ENABLE_BASIC_AUTH:-false}"
    volumes:
      - ./config/ocis/entrypoint-override.sh:/entrypoint-override.sh
      - ./config/ocis/mimetypes.json:/var/tmp/ocis/app-config/mimetypes.json
      - ocis-data:/var/lib/ocis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocis.entrypoints=https"
      - "traefik.http.routers.ocis.rule=Host(`${OCIS_DOMAIN:-ocis.owncloud.test}`)"
      - "traefik.http.routers.ocis.tls.certresolver=http"
      - "traefik.http.routers.ocis.service=ocis"
      - "traefik.http.services.ocis.loadbalancer.server.port=9200"
    logging:
      driver: "local"
    restart: always

  wopiserver-collabora:
    image: wkloucek/cs3-wopi-server:${WOPISERVER_DOCKER_TAG:-latest}
    networks:
      ocis-net:
    environment:
      WOPI_APP_NAME: Collabora
      WOPI_APP_DESCRIPTION: Collabora
      WOPI_APP_ICON: image-edit
      WOPI_JWT_SECRET: ${WOPI_JWT_SECRET:-LoremIpsum567}

      WOPI_GRPC_BIND_ADDR: 0.0.0.0:5678
      WOPI_GRPC_ADDR: wopiserver-collabora:5678

      WOPI_HTTP_BIND_ADDR: 0.0.0.0:6789
      WOPI_HTTP_ADDR: ${WOPISERVER_COLLABORA_DOMAIN:-wopiserver-collabora.owncloud.test}
      WOPI_HTTP_SCHEME: https

      WOPI_APP_ADDR: https://${COLLABORA_DOMAIN:-collabora.owncloud.test}
      WOPI_APP_INSECURE: "${INSECURE:-false}"

      WOPI_CS3API_ADDR: ocis:9142
      WOPI_CS3API_DATA_GATEWAY_INSECURE: "${INSECURE:-false}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wopiserver-collabora.entrypoints=https"
      - "traefik.http.routers.wopiserver-collabora.rule=Host(`${WOPISERVER_COLLABORA_DOMAIN:-wopiserver-collabora.owncloud.test}`)"
      - "traefik.http.routers.wopiserver-collabora.tls.certresolver=http"
      - "traefik.http.routers.wopiserver-collabora.service=wopiserver-collabora"
      - "traefik.http.services.wopiserver-collabora.loadbalancer.server.port=6789"
    logging:
      driver: "local"
    restart: always

  wopiserver-onlyoffice:
    image: wkloucek/cs3-wopi-server:${WOPISERVER_DOCKER_TAG:-latest}
    networks:
      ocis-net:
    environment:
      WOPI_APP_NAME: OnlyOffice
      WOPI_APP_DESCRIPTION: OnlyOffice
      WOPI_APP_ICON: image-edit
      WOPI_JWT_SECRET: ${WOPI_JWT_SECRET:-LoremIpsum567}

      WOPI_GRPC_BIND_ADDR: 0.0.0.0:5678
      WOPI_GRPC_ADDR: wopiserver-onlyoffice:5678

      WOPI_HTTP_BIND_ADDR: 0.0.0.0:6789
      WOPI_HTTP_ADDR: ${WOPISERVER_ONLYOFFICE_DOMAIN:-wopiserver-onlyoffice.owncloud.test}
      WOPI_HTTP_SCHEME: https

      WOPI_APP_ADDR: https://${ONLYOFFICE_DOMAIN:-onlyoffice.owncloud.test}
      WOPI_APP_INSECURE: "${INSECURE:-false}"

      WOPI_CS3API_ADDR: ocis:9142
      WOPI_CS3API_DATA_GATEWAY_INSECURE: "${INSECURE:-false}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wopiserver-onlyoffice.entrypoints=https"
      - "traefik.http.routers.wopiserver-onlyoffice.rule=Host(`${WOPISERVER_ONLYOFFICE_DOMAIN:-wopiserver-onlyoffice.owncloud.test}`)"
      - "traefik.http.routers.wopiserver-onlyoffice.tls.certresolver=http"
      - "traefik.http.routers.wopiserver-onlyoffice.service=wopiserver-onlyoffice"
      - "traefik.http.services.wopiserver-onlyoffice.loadbalancer.server.port=6789"
    logging:
      driver: "local"
    restart: always



  collabora:
    image: collabora/code:latest
    networks:
      ocis-net:
    environment:
      domain: ${OCIS_DOMAIN:-ocis.owncloud.test}
      DONT_GEN_SSL_CERT: "YES"
      extra_params: --o:ssl.enable=false --o:ssl.termination=true --o:welcome.enable=false --o:net.frame_ancestors=${OCIS_DOMAIN:-ocis.owncloud.test}
      username: ${COLLABORA_ADMIN_USER}
      password: ${COLLABORA_ADMIN_PASSWORD}
    cap_add:
      - MKNOD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora.entrypoints=https"
      - "traefik.http.routers.collabora.rule=Host(`${COLLABORA_DOMAIN:-collabora.owncloud.test}`)"
      - "traefik.http.routers.collabora.tls.certresolver=http"
      - "traefik.http.routers.collabora.service=collabora"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"
    logging:
      driver: "local"
    restart: always

  onlyoffice:
    image: onlyoffice/documentserver:6.4.0
    networks:
      ocis-net:
    environment:
      USE_UNAUTHORIZED_STORAGE: "${INSECURE:-false}" # selfsigned certificates
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onlyoffice.entrypoints=https"
      - "traefik.http.routers.onlyoffice.rule=Host(`${ONLYOFFICE_DOMAIN:-onlyoffice.owncloud.test}`)"
      - "traefik.http.routers.onlyoffice.tls.certresolver=http"
      - "traefik.http.routers.onlyoffice.service=onlyoffice"
      - "traefik.http.services.onlyoffice.loadbalancer.server.port=80"
      # websockets can't be opend when this is ommitted
      - "traefik.http.middlewares.onlyoffice.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.onlyoffice.middlewares=onlyoffice"
    logging:
      driver: "local"
    restart: always


volumes:
  certs:
  ocis-data:

networks:
  ocis-net:
