---
# OpenID Connect client registry.
clients:
  - id: phoenix
    name: OCIS
    application_type: web
    insecure: yes
    trusted: yes
    redirect_uris:
      - https://ocis.owncloud.test/
      - https://ocis.owncloud.test/oidc-callback.html
      - https://ocis.owncloud.test/oidc-silent-redirect.html
    origins:
      - https://ocis.owncloud.test

  - id: oc10
    name: OC10
    application_type: web
    secret: super
    insecure: yes
    trusted: yes
    redirect_uris:
      - https://oc10.owncloud.test/
      - https://oc10.owncloud.test/apps/openidconnect/redirect
    origins:
      - https://oc10.owncloud.test

  - id: ocis-explorer.js
    name: OCIS Graph Explorer
    trusted: yes
    application_type: web
    insecure: yes

  - id: xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69
    secret: UBntmLjC2yYCeHwsyj73Uwo9TAaecAetRwMw0xYcvNL9yRdLSUi0hUAHfvCHFeFh
    application_type: native
    insecure: true

  - id: e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD
    secret: dInFYGV33xKzhbRmpqQltYNdfLdJIfJ9L5ISoKhNoT9qZftpdWSP71VrpGR9pmoD
    application_type: native
    redirect_uris:
      - oc://android.owncloud.com

  - id: mxd5OQDk6es5LzOzRvidJNfXLUZS2oN3oUFeXPP8LpPrhx3UroJFduGEYIBOxkY1
    secret: KFeFWWEZO9TkisIQzR3fo7hfiMXlOpaqP8CFuTbSHzV1TUuGECglPxpiVKJfOXIx
    application_type: native
    redirect_uris:
      - oc://ios.owncloud.com
      - oc.ios://ios.owncloud.com
