---
debug:
  addr: 0.0.0.0:9129
  token:
  pprof: false
  zpages: false

http:
  addr: 0.0.0.0:9120

tracing:
  enabled: false
  type: jaeger
  endpoint: localhost:6831
  collector: http://localhost:14268/api/traces
  service: glauth

...
