---
- name: continuous-deployment-ocis-traefik-released
  server:
    server_type: cx21
    image: ubuntu-22.04
    location: nbg1
    initial_ssh_key_names:
      - owncloud-ocis@drone.owncloud.com
    labels:
      owner: ocis-team
      for: oCIS-continuous-deployment-examples
    rebuild: $REBUILD
    rebuild_carry_paths:
      - /var/lib/docker/volumes/ocis_certs

  domains:
    - "*.ocis-traefik.released.owncloud.works"

  vars:
    ssh_authorized_keys:
      - https://github.com/butonic.keys
      - https://github.com/fschade.keys
      - https://github.com/kulmann.keys
      - https://github.com/micbar.keys
      - https://github.com/rhafer.keys
      - https://github.com/wkloucek.keys
    docker_compose_projects:
      - name: ocis
        git_url: https://github.com/owncloud/ocis.git
        ref: master
        docker_compose_path: deployments/examples/ocis_traefik
        env:
          INSECURE: "false"
          TRAEFIK_ACME_MAIL: mbarz@owncloud.com
          OCIS_DOCKER_TAG: 5.0.8
          OCIS_DOMAIN: ocis.ocis-traefik.released.owncloud.works
          DEMO_USERS: "true"
          INBUCKET_DOMAIN: mail.ocis-traefik.released.owncloud.works
          COMPOSE_FILE: docker-compose.yml:monitoring_tracing/docker-compose-additions.yml
      - name: monitoring
        git_url: https://github.com/owncloud-devops/monitoring-tracing-client.git
        ref: master
        env:
          NETWORK_NAME: ocis-net
          TELEMETRY_SERVE_DOMAIN: telemetry.ocis-traefik.released.owncloud.works
          JAEGER_COLLECTOR: jaeger-collector.infra.owncloud.works:443
          TELEGRAF_SPECIFIC_CONFIG: ocis_single_container
          OCIS_URL: ocis.ocis-traefik.released.owncloud.works
          OCIS_DEPLOYMENT_ID: continuous-deployment-ocis-traefik-released
