---
version: "3.7"

services:
  ocis:
    environment:
      # tracing
      OCIS_TRACING_ENABLED: "true"
      OCIS_TRACING_ENDPOINT: jaeger-agent:6831
      # metrics
      APP_PROVIDER_DEBUG_ADDR: 0.0.0.0:9165
      GLAUTH_DEBUG_ADDR: 0.0.0.0:9129
      GRAPH_DEBUG_ADDR: 0.0.0.0:9124
      GRAPH_EXPLORER_DEBUG_ADDR: 0.0.0.0:9136
      IDP_DEBUG_ADDR: 0.0.0.0:9134
      OCS_DEBUG_ADDR: 0.0.0.0:9114
      PROXY_DEBUG_ADDR: 0.0.0.0:9205
      SETTINGS_DEBUG_ADDR: 0.0.0.0:9194
      STORAGE_AUTH_BASIC_DEBUG_ADDR: 0.0.0.0:9147
      STORAGE_AUTH_BEARER_DEBUG_ADDR: 0.0.0.0:9149
      STORAGE_AUTH_MACHINE_DEBUG_ADDR: 0.0.0.0:9167
      STORAGE_FRONTEND_DEBUG_ADDR: 0.0.0.0:9141
      STORAGE_GATEWAY_DEBUG_ADDR: 0.0.0.0:9143
      STORAGE_GROUPPROVIDER_DEBUG_ADDR: 0.0.0.0:9161
      STORAGE_HOME_DEBUG_ADDR: 0.0.0.0:9156
      STORAGE_METADATA_DEBUG_ADDR: 0.0.0.0:9217
      STORAGE_PUBLIC_LINK_DEBUG_ADDR: 0.0.0.0:9179
      STORAGE_USERPROVIDER_DEBUG_ADDR: 0.0.0.0:9145
      STORAGE_USERS_DEBUG_ADDR: 0.0.0.0:9159
      STORAGES_SHARING_DEBUG_ADDR: 0.0.0.0:9151
      STORE_DEBUG_ADDR: 0.0.0.0:9460
      THUMBNAILS_DEBUG_ADDR: 0.0.0.0:9189
      WEB_DEBUG_ADDR: 0.0.0.0:9104
      WEBDAV_DEBUG_ADDR: 0.0.0.0:9119

networks:
  ocis-net:
    external: true
