baseURL = "https://owncloud.github.io/ocis-ocs/"
languageCode = "en-us"
title = "ownCloud Infinite Scale: OCS"
pygmentsUseClasses = true

disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap"]

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

[params]
  author = "ownCloud GmbH"
  description = "Serve OCS API for Reva/oCIS"
  keywords = "reva, ocis"
