baseURL = "https://owncloud.github.io/ocis-graph/"
languageCode = "en-us"
title = "ownCloud Infinite Scale: graph"
pygmentsUseClasses = true

disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap"]

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

[params]
  author = "ownCloud GmbH"
  description = "Example service for Reva/oCIS"
  keywords = "reva, ocis"
